{% set data = load_setup_py_data() %}
{% set version = data.get('version') or 'placehold' %}

package:
  name: q2-quality-control
  version: {{ version }}

source:
  path: ../..

build:
  script: make install

requirements:
  host:
    - python {{ python }}
    - setuptools

  run:
    - python {{ python }}
    - pandas {{ pandas }}
    - seaborn
    - blast >=2.6.0
    # There are issues with 2.8.2, and no OS X builds exist after 2.7.0
    - vsearch <=2.7.0
    - samtools >=1.15
    - bowtie2
    - qiime2 {{ qiime2_epoch }}.*
    - q2-types {{ qiime2_epoch }}.*
    - q2templates {{ qiime2_epoch }}.*
    - q2-taxa {{ qiime2_epoch }}.*
    - biom-format {{ biom_format }}

test:
  requires:
    - qiime2 >={{ qiime2 }}
    - q2-types >={{ q2_types }}
    - q2templates >={{ q2templates }}
    - q2-taxa >={{ q2_taxa }}
    - pytest

  imports:
    - q2_quality_control
    - qiime2.plugins.quality_control

about:
  home: https://qiime2.org
  license: BSD-3-Clause
  license_family: BSD
