{% set data = load_setup_py_data() %}
{% set version = data.get('version') or 'placehold' %}
{% set release = '.'.join(version.split('.')[:2]) %}

package:
  name: q2-quality-control
  version: {{ version }}

source:
  path: ../..

build:
  script: make install

requirements:
  host:
    - python {{ python }}
    - setuptools

  run:
    - python {{ python }}
    - pandas >=1
    - seaborn
    - blast >=2.6.0
    # There are issues with 2.8.2, and no OS X builds exist after 2.7.0
    - vsearch <=2.7.0
    - samtools >=1.7
    - bowtie2
    - qiime2 {{ release }}.*
    - q2-types {{ release }}.*
    - q2templates {{ release }}.*
    - q2-taxa {{ release }}.*
    # TODO: revert this pin
    # https://www.biostars.org/p/494922/
    - tbb 2020.2

test:
  imports:
    - q2_quality_control
    - qiime2.plugins.quality_control

about:
  home: https://qiime2.org
  license: BSD-3-Clause
  license_family: BSD
